### PR TITLE
Fix assertion failing if arg already has the expected shape.

### PR DESCRIPTION
**Pull request by WarmongeringBeaver**
An `assert` was checking if `bm_cube.shape == (nant, bm_pix, bm_pix)`, _then_ doing `bm_cube = bm_cube[np.newaxis, np.newaxis]`, causing a `hera_sim` test to fail because the provided `bm_cube` already had shape `(1, 1, nant, bm_pix, bm_pix)`.

-> Test first if `bm_cube` already has shape `(1, 1, nant, bm_pix, bm_pix)`.

(Also, improve info given by the `AssertionError` message by explicitly giving the wanted/given shapes.)

### CODE REVIEW

**Review by steven-murray — APPROVED** [review]
Thanks @WarmongeringBeaver, this looks perfect.

**Comment by WarmongeringBeaver** [comment]
Actually I got mixed up between the `try`, `except` & `assert` syntax, the tests should pass now; sorry for this.

**Comment by steven-murray** [comment]
@WarmongeringBeaver you should (locally) do

```
pip install pre-commit
pre-commit install
pre-commit run -a
```

Looks like you might need to add a single test to cover the new code as well.

**Comment by philbull** [comment]
Merging this as approved.

**Pull request merged**
